apiVersion: v2
name: mission-control-watchtower
description: Mission Control Helm Chart for monitoring mission-control itself
type: application
version: 0.1.35-beta.3
appVersion: "1.0.0"
maintainers:
  - name: Flanksource
