nameOverride: ""
fullnameOverride: ""
labels: {}
topologyName: mission-control
connectionName: mission-control-db
isAgent: false
playbooks: true
pushLocation:
  url: ''
topology:
  enabled: true
views:
  enabled: true
  unhealthyConfigs: true
  pods: true
# username:
#   valueFrom:
#     secretKeyRef:
#       key: ''
#       name: ''
# password:
#   valueFrom:
#     secretKeyRef:
#       key: ''
#       name: ''
