# yaml-language-server: $schema=values.schema.json
# Values files
nameOverride: ""
fullnameOverride: ""

# @schema
# required: false
# type: string
# @schema
prometheusURL: ""

# @schema
# type: object
# additionalProperties: true
# required: false
# @schema
labels: {}

# @schema
# type: string
# required: true
# @schema
topologyName: mission-control

# @schema
# type: string
# required: true
# @schema
connectionName: mission-control-db

# @schema
# type: boolean
# required: false
# @schema
isAgent: false

# @schema
# type: boolean
# required: false
# @schema
playbooks: true

# @schema
# type: object
# required: false
# @schema
pushLocation:
  # @schema
  # required: false
  # type: string
  # @schema
  url: ""

# @schema
# type: object
# required: false
# @schema
topology:
  enabled: true

# @schema
# required: false
# @schema
views:
  # If this is set to false, no views will be created
  enabled: true

  # @schema
  # type: object
  # required: false
  # @schema
  unhealthyConfigs:
    # @schema
    # required: false
    # default: true
    # type: boolean
    # @schema
    enabled: true
    # @schema
    # required: false
    # type: boolean
    # default: true
    # @schema
    sidebar: true

  # @schema
  # required: false
  # @schema
  pods:
    # @schema
    # required: false
    # default: false
    # type: boolean
    # @schema
    enabled: false
    # @schema
    # required: false
    # type: boolean
    # default: false
    # @schema
    sidebar: false
# username:
#   valueFrom:
#     secretKeyRef:
#       key: ''
#       name: ''
# password:
#   valueFrom:
#     secretKeyRef:
#       key: ''
#       name: ''
