apiVersion: v2
name: mission-control-misc-playbooks
description: A Helm chart for miscellaneous Mission Control playbooks (kubectl, curl)
icon: https://github.com/flanksource/docs/blob/main/docs/images/flanksource-icon.png?raw=true
type: application
version: 0.1.2-beta.1
appVersion: "1.0.0"
maintainers:
  - name: Flanksource
