apiVersion: v2
name: mission-control-kubernetes-view
description: A Helm chart for Kubernetes views in Flanksource Mission Control
icon: https://github.com/flanksource/docs/blob/main/docs/images/flanksource-icon.png?raw=true
type: application
version: 0.1.18-beta.1
appVersion: "1.0.0"
maintainers:
  - name: Flanksource
