# yaml-language-server: $schema=values.schema.json

# Field that can be used as a condition when kubernetes-view is a dependency.
# This definition is only here as a placeholder such that it is included in
# the json schema.
# See https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags
# for more info.
# +docs:hidden
enabled: true

# @schema
# required: false
# @schema
# @ignored
nameOverride: ""
# @schema
# required: false
# @schema
# @ignored
fullnameOverride: ""
# @schema
# required: false
# additionalProperties: true
# @schema
labels: {}

# @schema
# required: false
# additionalProperties: true
# @schema
global:
  # @schema
  # required: false
  # @schema
  prometheus:
    # @schema
    # required: false
    # default: ""
    # @schema
    connection: ""

# @schema
# required: false
# @schema
views:
  # If this is set to false, no views will be created
  enabled: true

  # @schema
  # required: false
  # @schema
  namespace:
    # @schema
    # required: false
    # default: true
    # type: boolean
    # @schema
    enabled: true
    # @schema
    # required: false
    # @schema
    deployments:
      # @schema
      # required: false
      # default: true
      # type: boolean
      # @schema
      enabled: true
    # @schema
    # required: false
    # @schema
    helmReleases:
      # @schema
      # required: false
      # default: true
      # type: boolean
      # @schema
      enabled: true
    # @schema
    # required: false
    # @schema
    ingress:
      # @schema
      # required: false
      # default: true
      # type: boolean
      # @schema
      enabled: true

  # @schema
  # required: false
  # @schema
  ingress:
    # @schema
    # required: false
    # default: true
    # type: boolean
    # @schema
    enabled: true
    # @schema
    # required: false
    # type: boolean
    # default: true
    # @schema
    sidebar: true

  # @schema
  # required: false
  # @schema
  helmReleases:
    # @schema
    # required: false
    # default: true
    # @schema
    enabled: true
    # @schema
    # required: false
    # default: true
    # @schema
    sidebar: true

  # @schema
  # required: false
  # @schema
  deployments:
    # @schema
    # required: false
    # default: true
    # @schema
    enabled: true
    # @schema
    # required: false
    # default: true
    # @schema
    sidebar: true

  # @schema
  # required: false
  # @schema
  pods:
    # @schema
    # required: false
    # default: true
    # @schema
    enabled: true
    # @schema
    # required: false
    # default: true
    # @schema
    sidebar: true

  # @schema
  # required: false
  # @schema
  pod:
    # @schema
    # required: false
    # default: true
    # @schema
    enabled: true

  # @schema
  # required: false
  # @schema
  clusterOverview:
    # @schema
    # required: false
    # default: true
    # @schema
    enabled: true
    # @schema
    # required: false
    # default: true
    # @schema
    sidebar: true

  # @schema
  # required: false
  # @schema
  nodes:
    # @schema
    # required: false
    # default: true
    # @schema
    enabled: true
    # @schema
    # required: false
    # default: true
    # @schema
    sidebar: true
