apiVersion: v2
name: mission-control-mssql
description: Flanksource Mission Control bundle for managing MSSQL servers and databases.
icon: https://github.com/flanksource/docs/blob/main/docs/images/flanksource-icon.png?raw=true
type: application
version: 0.1.1-beta.8
appVersion: "1.0.0"
maintainers:
  - name: Flanksource
