# yaml-language-server: $schema=values.schema.json

# @schema
# required: false
# @schema
rbac:
  # @schema
  # type: boolean
  # required: false
  # @schema
  # -- create a ClusterRole with the necessary permissions for flux CLI actions
  create: false
  # @schema
  # type: string
  # required: false
  # @schema
  # -- name of the ClusterRole to create
  clusterRoleName: playbooks-flux
  # @schema
  # type: string
  # required: false
  # @schema
  # -- serviceAccount to bind the ClusterRole to
  serviceAccount: mission-control-sa
  # @schema
  # type: string
  # required: false
  # @schema
  # -- namespace of the serviceAccount
  serviceAccountNamespace: mission-control

createPullRequest: true
git:
  # Git connection to use when opening Pull Requests and pushing changes
  # @schema
  # required: true
  # example: connection://mission-control/github
  # @schema
  connection:
  # URL for the default git repository to use
  # @schema
  # required: false
  # example: https://github.com/flanksource/demo-gitops.git
  # @schema
  url:
  type: github
playbooks:
  enabled: true
  resume: true
  suspend: true
  reconcile: true
  edit: true
  debug: false
  createDeployment: true
  updateHelmValues: true
  updateHelmChartVersion: true
  createHelmRelease: true
  updateResources: true
  updateImage: true
  scale: true
  requestNamespaceAccess: true
