{{- if and .Values.views.enabled .Values.views.namespace.enabled .Values.views.namespace.helmReleases.enabled }}
apiVersion: mission-control.flanksource.com/v1
kind: View
metadata:
  name: namespace-helmreleases
  labels:
    {{- include "kubernetes-view.labels" . | nindent 4 }}
spec:
  display:
    title: Namespace Helm Releases
    icon: rocket
    sidebar: false
    card:
      default: true
  templating:
    - key: cluster
      label: Cluster
      valueFrom:
        config:
          agent: "all"
          types:
            - Kubernetes::Cluster
    - key: namespace
      label: Namespace
      dependsOn:
        - cluster
      valueFrom:
        config:
          agent: "all"
          tagSelector: "cluster=$(.var.cluster)"
          types:
            - Kubernetes::Namespace
  panels:
    - name: Health
      description: Helm Releases grouped by health
      type: piechart
      piechart:
        showLabels: true
        colors:
          healthy: "#28C19B"
          unhealthy: "#F04E6E"
          unknown: "#666666"
          warning: "#F4B23C"
      query: SELECT COUNT(*) AS count, health FROM helm_releases GROUP BY health
    - name: Status
      description: Helm Releases grouped by status
      type: piechart
      piechart:
        colors:
          InstallSucceeded: "#28C19B"
          RollbackSucceeded: "#F4B23C"
          UpgradeFailed: "#F04E6E"
          UpgradeSucceeded: "#5965F2"
          Reconciling: "#666666"
      query: SELECT COUNT(*) AS count, status FROM helm_releases GROUP BY status
  columns:
    - name: id
      type: string
      description: The id of the deployment.
      primaryKey: true
      hidden: true
    - name: application
      type: string
      description: The application name.
      card:
        position: title
      url:
        config: row.id
    - name: chart
      type: string
      description: The chart name.
      card:
        position: body
    - name: version
      type: string
      description: The version of the deployment.
      card:
        position: body
    - name: status
      type: status
      icon: row.health
      description: The status of the deployment.
      card:
        position: subtitle
      filter:
        type: multiselect
    - name: health
      type: health
      hidden: true
      description: The health of the deployment.
      card:
        useForAccent: true
      filter:
        type: multiselect
    - name: lastUpdated
      type: datetime
      description: The last updated time.
      card:
        position: body
  queries:
    helm_releases:
      configs:
        tagSelector: "cluster=$(.var.cluster),namespace=$(.var.namespace)"
        agent: "all"
        types:
          - Kubernetes::HelmRelease
  mapping:
    application: row.name
    namespace: row.tags.namespace
    chart: row.config.spec.chart.spec.chart
    version: >
      has(row.config.status.lastAttemptedRevision) ? row.config.status.lastAttemptedRevision : "unknown"
    lastUpdated: row.updated_at
{{- end }}
